[package]
name = "mdbook_preprocessor"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.14.0"
mdbook = "0.4.52"
regex = "1.12.2"
serde_json = "1.0.145"
toml = "0.5.11"
